"use client";

import Image from "next/image";
import Link from "next/link";

const gallery = ["/images/concerns/eco-agro.png", "/images/concerns/3-sampan-eco-agro.png", "/images/logos/3-sampan-eco-agro.png"];

export default function EcoAgroModernPage() {
  return <main className="eco-modern-page bg-[#f4f2ea] text-[#17251f]"><style>{`@media (min-width: 1024px) { .eco-modern-page section:not(:first-of-type) > div { max-width: 1100px !important; margin-left: auto; margin-right: auto; padding-left: 3.5rem !important; padding-right: 3.5rem !important; } .eco-modern-page section:first-of-type > div.absolute { max-width: none !important; padding: 0 !important; } .eco-modern-page h1 { font-size: clamp(3.1rem, 5vw, 5.8rem); } .eco-modern-page h2 { font-size: clamp(2.4rem, 3.6vw, 4.2rem); } }`}</style>
    <section className="relative flex min-h-[92svh] items-end overflow-hidden bg-[#10231b] text-white"><video autoPlay muted loop playsInline className="absolute inset-0 h-full w-full object-cover opacity-60"><source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-gradient-to-t from-[#10231b] via-[#10231b]/30 to-transparent" /><div className="relative z-10 mx-auto w-full max-w-[1400px] px-6 pb-16 sm:px-8 lg:px-12 lg:pb-24"><p className="text-xs font-semibold uppercase tracking-[0.32em] text-[#a8df73]">Sampan Eco &amp; Agro</p><h1 className="mt-5 max-w-5xl text-5xl font-medium leading-[0.95] tracking-[-0.045em] sm:text-7xl lg:text-[clamp(4rem,7vw,7.5rem)]">Growing a better<br />way forward.</h1><div className="mt-8 flex flex-wrap items-center gap-5"><p className="max-w-md text-base leading-7 text-white/75">A living destination where responsible agriculture, fresh food and restorative experiences meet.</p><Link href="#story" className="border border-white/60 px-6 py-3 text-xs font-semibold uppercase tracking-[0.18em] transition hover:bg-white hover:text-[#10231b]">Explore the resort <span className="ml-3">↓</span></Link></div></div></section>
    <section id="story" className="bg-[#f4f2ea] py-24 lg:py-36"><div className="mx-auto grid w-full max-w-[1400px] gap-14 px-6 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:gap-28 lg:px-12"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#4e7259]">01 -  The idea</p><div><h2 className="max-w-4xl text-4xl font-medium leading-[1.05] tracking-[-0.035em] sm:text-6xl">The countryside is not somewhere to escape to. It is somewhere to reconnect.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-black/60">Sampan Eco &amp; Agro is a new kind of destination: rooted in the soil, generous in spirit and designed around a healthier relationship with nature.</p></div></div></section>
    <section className="bg-[#dfe9dc] py-24 lg:py-32"><div className="mx-auto grid w-full max-w-[1400px] gap-14 px-6 sm:px-8 lg:grid-cols-2 lg:items-center lg:gap-24 lg:px-12"><div className="relative aspect-[4/5] overflow-hidden"><Image src="/images/concerns/eco-agro.png" alt="Fresh produce from Sampan Eco and Agro" fill className="object-cover" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#4e7259]">02 -  From farm to table</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-tight tracking-tight sm:text-5xl">Freshness you can see, taste and trust.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-black/60">We cultivate with care and bring the best of the harvest closer to the people who enjoy it. Every detail is connected—from the land we protect to the food we share.</p><Link href="#visit" className="mt-9 inline-flex border border-[#17251f] px-7 py-4 text-xs font-semibold uppercase tracking-[0.18em] transition hover:bg-[#17251f] hover:text-white">Discover our approach <span className="ml-4">↗</span></Link></div></div></section>
    <section className="bg-[#10231b] py-24 text-white lg:py-32"><div className="mx-auto w-full max-w-[1400px] px-6 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#a8df73]">03 -  The experience</p><h2 className="mt-5 max-w-3xl text-4xl font-medium leading-tight tracking-tight sm:text-6xl">More than a farm.<br />A place to feel alive.</h2></div><p className="max-w-sm text-base leading-7 text-white/60">Spend time outdoors, share a meal, discover new flavours and leave with a different sense of pace.</p></div><div className="mt-16 grid divide-y divide-white/15 border-y border-white/15 md:grid-cols-3 md:divide-x md:divide-y-0">{[{n:"01",t:"Grow",d:"Responsible cultivation and seasonal produce."},{n:"02",t:"Gather",d:"Thoughtful spaces for food, family and community."},{n:"03",t:"Restore",d:"Open landscapes that make room to breathe."}].map((item)=><article key={item.n} className="px-0 py-8 md:px-8 md:py-10 first:md:pl-0"><p className="text-sm text-[#a8df73]">{item.n}</p><h3 className="mt-10 text-2xl font-medium">{item.t}</h3><p className="mt-3 max-w-xs text-white/55">{item.d}</p></article>)}</div></div></section>
    <section className="py-24 lg:py-32"><div className="mx-auto w-full max-w-[1400px] px-6 sm:px-8 lg:px-12"><div className="flex items-end justify-between gap-8"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#4e7259]">04 -  A sense of place</p><h2 className="mt-5 text-4xl font-medium tracking-tight sm:text-6xl">Come closer.</h2></div><p className="hidden max-w-sm text-right text-black/55 sm:block">A few frames from a destination still taking shape.</p></div><div className="mt-12 grid gap-5 md:grid-cols-[1.25fr_0.75fr]"><div className="relative h-[30rem] overflow-hidden md:h-[38rem]"><Image src={gallery[0]} alt="Sampan Eco and Agro" fill className="object-cover" /></div><div className="grid gap-5"><div className="relative h-56 overflow-hidden md:h-auto"><Image src={gallery[1]} alt="Sampan Eco and Agro fields" fill className="object-cover" /></div><div className="flex items-end justify-between bg-[#dfe9dc] p-7"><p className="max-w-xs text-xl leading-snug">A greener future starts with the places we choose to build.</p><span className="text-3xl">↘</span></div></div></div></div></section>
    <section id="visit" className="bg-[#b8d88d] py-20 lg:py-28"><div className="mx-auto flex w-full max-w-[1400px] flex-col justify-between gap-8 px-6 sm:px-8 lg:flex-row lg:items-center lg:px-12"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#31533b]">05 -  Plan your visit</p><h2 className="mt-4 max-w-2xl text-4xl font-medium tracking-tight sm:text-5xl">Make room for something real.</h2></div><Link href="/contact" className="inline-flex w-fit items-center border border-[#17251f] px-7 py-4 text-xs font-semibold uppercase tracking-[0.18em] transition hover:bg-[#17251f] hover:text-white">Talk to Sampan <span className="ml-4">↗</span></Link></div></section>
  </main>;
}
