import Image from "next/image";
import Link from "next/link";

const hero = "/images/projects/Sampan-White-House-&-Motel.png";
const motel = "/images/concerns/highway-motel.png";
const facilities = [
  ["Comfortable rooms", "A calm place to rest before the road continues."],
  ["Secure parking", "Convenient parking for guests traveling by car."],
  ["Flexible stays", "Short breaks, day use, and overnight stays."],
  ["Family-friendly spaces", "Room to pause, refresh, and spend time together."],
  ["Travel assistance", "Helpful guidance for routes and onward travel."],
  ["On-site hospitality", "A welcoming team and nearby dining."],
];
const packages = ["Short stay", "Day stay", "Overnight stay"];
const gallery = [hero, motel, "/images/facilities/highway_inn/Official-Outing.png"];
const map = "https://www.google.com/maps?q=Sampan%20Highway%20Motel%20White%20House%20Bangladesh&output=embed";

export const metadata = { title: "Sampan Highway Motel & White House | Sampan Group", description: "A comfortable highway stop for rest, refreshment, and onward travel." };

export default function HighwayMotelWhiteHousePage() {
  return <main className="bg-[#f5f6f1] text-[#183b2b]">
    <section className="relative flex min-h-[88vh] items-end overflow-hidden bg-[#123b2c] text-white"><Image src={hero} alt="Sampan Highway Motel and White House" fill priority sizes="100vw" className="object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-[#071b13] via-[#123b2c]/45 to-transparent" /><div className="relative z-10 mx-auto w-full max-w-[1400px] px-6 pb-16 sm:px-10 lg:px-16 lg:pb-24"><p className="text-xs font-semibold uppercase tracking-[0.35em] text-[#ef636b]">Sampan hospitality</p><h1 className="mt-5 max-w-4xl text-[clamp(2.8rem,7vw,6.8rem)] font-medium leading-[0.9] tracking-[-0.055em]">A softer place<br /><span className="text-[#ef636b]">to stop.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/75 sm:text-lg">Sampan Highway Motel &amp; White House gives travelers a comfortable pause, close to the route and ready for what comes next.</p><div className="mt-9 flex flex-wrap gap-3"><a href="tel:+8801929918408" className="bg-[#ef636b] px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em]">Book or enquire</a><Link href="#location" className="border border-white/60 px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em]">Find us ↓</Link></div></div></section>

<<<<<<< HEAD
    <section className="mx-auto grid max-w-[1400px] gap-10 px-6 py-20 sm:px-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24 lg:px-16 lg:py-32"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#16815b]">01 — Overview</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-[0.98] sm:text-6xl">Rest easy before you continue.</h2></div><div className="max-w-2xl"><p className="text-xl leading-9 text-[#183b2b]/75 sm:text-2xl">Not just somewhere you stop. Somewhere you can reset, refresh, and make the next part of the journey feel easier.</p><p className="mt-7 leading-7 text-[#183b2b]/60">Flexible stays, dependable hospitality, and a location that keeps you close to the highway.</p></div></section>

    <section className="bg-[#e7efe9] px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#ef636b]">02 — Facilities &amp; offerings</p><h2 className="mt-5 max-w-2xl text-4xl font-medium leading-tight sm:text-6xl">Everything you need for a comfortable journey.</h2><div className="mt-14 grid border-t border-[#183b2b]/15 sm:grid-cols-2 lg:grid-cols-3">{facilities.map(([title, description], i) => <article key={title} className="border-b border-[#183b2b]/15 p-6 pl-0 sm:p-8 sm:pl-0 lg:border-r lg:border-[#183b2b]/15"><span className="text-sm text-[#ef636b]">0{i + 1}</span><h3 className="mt-10 text-xl font-medium">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#183b2b]/60">{description}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-[1400px] px-6 py-20 sm:px-10 lg:px-16 lg:py-32"><div className="grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:gap-24"><div className="relative aspect-[4/3] overflow-hidden"><Image src={motel} alt="Sampan Highway Motel White House" fill className="object-cover" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#16815b]">03 — Room &amp; package overview</p><h2 className="mt-5 text-4xl font-medium leading-tight sm:text-5xl">Choose the pause that fits your route.</h2><div className="mt-10 divide-y divide-[#183b2b]/15 border-y border-[#183b2b]/15">{packages.map((item, i) => <div key={item} className="flex items-center justify-between py-6"><div><h3 className="text-xl font-medium">{item}</h3><p className="mt-2 text-sm text-[#183b2b]/60">Comfortable accommodation planned around your journey.</p></div><span className="text-sm text-[#ef636b]">0{i + 1}</span></div>)}</div><a href="tel:+8801929918408" className="mt-8 inline-flex bg-[#16815b] px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-white">Ask about availability</a></div></div></section>

    <section className="bg-[#183b2b] px-6 py-20 text-white sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#ef636b]">04 — The journey</p><h2 className="mt-5 max-w-3xl text-4xl font-medium leading-tight sm:text-6xl">A dependable stop between destinations.</h2><div className="mt-14 grid border-y border-white/15 md:grid-cols-3">{[["Dhaka", "Start your journey"], ["Sampan Highway Motel", "Pause, refresh, continue"], ["Your destination", "Arrive ready"]].map(([title, detail], i) => <div key={title} className="border-b border-white/15 py-8 md:border-b-0 md:border-r md:px-8 md:last:border-0"><span className="text-sm text-[#ef636b]">0{i + 1}</span><h3 className="mt-10 text-2xl font-medium">{title}</h3><p className="mt-2 text-sm text-white/55">{detail}</p></div>)}</div></div></section>

    <section className="px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#ef636b]">05 — Inside White House</p><h2 className="mt-4 text-4xl font-medium sm:text-6xl">A look around.</h2><div className="mt-12 grid gap-5 md:grid-cols-[1.2fr_0.8fr]">{gallery.map((src, i) => <div key={src} className={`relative overflow-hidden ${i === 0 ? "aspect-[4/3] md:row-span-2 md:aspect-auto" : "aspect-[4/3]"}`}><Image src={src} alt="Sampan Highway Motel gallery" fill className="object-cover" /></div>)}</div></div></section>

    <section id="location" className="bg-[#e7efe9] px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto grid max-w-[1400px] gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20 lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#16815b]">06 — Location &amp; map</p><h2 className="mt-5 text-4xl font-medium leading-tight sm:text-5xl">Easy to find. Easy to continue from.</h2><a href="https://www.google.com/maps/search/?api=1&query=Sampan+Highway+Motel+White+House+Bangladesh" target="_blank" rel="noreferrer" className="mt-8 inline-flex border border-[#183b2b] px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em]">Open directions ↗</a></div><div className="aspect-[16/9] overflow-hidden border border-[#183b2b]/15"><iframe title="Sampan Highway Motel and White House map" src={map} className="h-full w-full border-0" loading="lazy" /></div></div></section>

    <section className="bg-[#ef636b] px-6 py-20 text-[#183b2b] sm:px-10 lg:px-16 lg:py-24"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.3em]">07 — Plan your stop</p><h2 className="mt-4 max-w-2xl text-4xl font-medium leading-tight sm:text-6xl">Make the pause part of the plan.</h2></div><a href="tel:+8801929918408" className="inline-flex w-fit border border-[#183b2b] px-7 py-4 text-xs font-semibold uppercase tracking-[0.16em]">Call +880 1929-918408</a></div></section>
=======
    <section className="mx-auto grid max-w-[1400px] gap-10 px-6 py-20 sm:px-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24 lg:px-16 lg:py-32"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#16815b]">01 -  Overview</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-[0.98] sm:text-6xl">Rest easy before you continue.</h2></div><div className="max-w-2xl"><p className="text-xl leading-9 text-[#183b2b]/75 sm:text-2xl">Not just somewhere you stop. Somewhere you can reset, refresh, and make the next part of the journey feel easier.</p><p className="mt-7 leading-7 text-[#183b2b]/60">Flexible stays, dependable hospitality, and a location that keeps you close to the highway.</p></div></section>

    <section className="bg-[#e7efe9] px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#ef636b]">02 -  Facilities &amp; offerings</p><h2 className="mt-5 max-w-2xl text-4xl font-medium leading-tight sm:text-6xl">Everything you need for a comfortable journey.</h2><div className="mt-14 grid border-t border-[#183b2b]/15 sm:grid-cols-2 lg:grid-cols-3">{facilities.map(([title, description], i) => <article key={title} className="border-b border-[#183b2b]/15 p-6 pl-0 sm:p-8 sm:pl-0 lg:border-r lg:border-[#183b2b]/15"><span className="text-sm text-[#ef636b]">0{i + 1}</span><h3 className="mt-10 text-xl font-medium">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#183b2b]/60">{description}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-[1400px] px-6 py-20 sm:px-10 lg:px-16 lg:py-32"><div className="grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:gap-24"><div className="relative aspect-[4/3] overflow-hidden"><Image src={motel} alt="Sampan Highway Motel White House" fill className="object-cover" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#16815b]">03 -  Room &amp; package overview</p><h2 className="mt-5 text-4xl font-medium leading-tight sm:text-5xl">Choose the pause that fits your route.</h2><div className="mt-10 divide-y divide-[#183b2b]/15 border-y border-[#183b2b]/15">{packages.map((item, i) => <div key={item} className="flex items-center justify-between py-6"><div><h3 className="text-xl font-medium">{item}</h3><p className="mt-2 text-sm text-[#183b2b]/60">Comfortable accommodation planned around your journey.</p></div><span className="text-sm text-[#ef636b]">0{i + 1}</span></div>)}</div><a href="tel:+8801929918408" className="mt-8 inline-flex bg-[#16815b] px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em] text-white">Ask about availability</a></div></div></section>

    <section className="bg-[#183b2b] px-6 py-20 text-white sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#ef636b]">04 -  The journey</p><h2 className="mt-5 max-w-3xl text-4xl font-medium leading-tight sm:text-6xl">A dependable stop between destinations.</h2><div className="mt-14 grid border-y border-white/15 md:grid-cols-3">{[["Dhaka", "Start your journey"], ["Sampan Highway Motel", "Pause, refresh, continue"], ["Your destination", "Arrive ready"]].map(([title, detail], i) => <div key={title} className="border-b border-white/15 py-8 md:border-b-0 md:border-r md:px-8 md:last:border-0"><span className="text-sm text-[#ef636b]">0{i + 1}</span><h3 className="mt-10 text-2xl font-medium">{title}</h3><p className="mt-2 text-sm text-white/55">{detail}</p></div>)}</div></div></section>

    <section className="px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#ef636b]">05 -  Inside White House</p><h2 className="mt-4 text-4xl font-medium sm:text-6xl">A look around.</h2><div className="mt-12 grid gap-5 md:grid-cols-[1.2fr_0.8fr]">{gallery.map((src, i) => <div key={src} className={`relative overflow-hidden ${i === 0 ? "aspect-[4/3] md:row-span-2 md:aspect-auto" : "aspect-[4/3]"}`}><Image src={src} alt="Sampan Highway Motel gallery" fill className="object-cover" /></div>)}</div></div></section>

    <section id="location" className="bg-[#e7efe9] px-6 py-20 sm:px-10 lg:px-16 lg:py-28"><div className="mx-auto grid max-w-[1400px] gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20 lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-[#16815b]">06 -  Location &amp; map</p><h2 className="mt-5 text-4xl font-medium leading-tight sm:text-5xl">Easy to find. Easy to continue from.</h2><a href="https://www.google.com/maps/search/?api=1&query=Sampan+Highway+Motel+White+House+Bangladesh" target="_blank" rel="noreferrer" className="mt-8 inline-flex border border-[#183b2b] px-6 py-3 text-xs font-semibold uppercase tracking-[0.16em]">Open directions ↗</a></div><div className="aspect-[16/9] overflow-hidden border border-[#183b2b]/15"><iframe title="Sampan Highway Motel and White House map" src={map} className="h-full w-full border-0" loading="lazy" /></div></div></section>

    <section className="bg-[#ef636b] px-6 py-20 text-[#183b2b] sm:px-10 lg:px-16 lg:py-24"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.3em]">07 -  Plan your stop</p><h2 className="mt-4 max-w-2xl text-4xl font-medium leading-tight sm:text-6xl">Make the pause part of the plan.</h2></div><a href="tel:+8801929918408" className="inline-flex w-fit border border-[#183b2b] px-7 py-4 text-xs font-semibold uppercase tracking-[0.16em]">Call +880 1929-918408</a></div></section>
>>>>>>> aef522dae09b0fc347a0c78d64f55c28cd86a0bf

    <section className="px-6 py-16 sm:px-10 lg:px-16 lg:py-20"><div className="mx-auto grid max-w-[1400px] gap-6 border-t border-[#183b2b]/15 pt-8 text-sm text-[#183b2b]/60 sm:grid-cols-2 lg:grid-cols-4">{["Milestone counter", "Guest reviews", "Virtual tour", "Press & media"].map((item) => <div key={item}><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#16815b]">{item}</p><p className="mt-3 text-2xl font-medium text-[#183b2b]">Coming soon</p><p className="mt-1">Verified content will be added when supplied.</p></div>)}</div></section>
  </main>;
}
