import Image from "next/image";
import Link from "next/link";
import EcoAgroStory from "@/components/EcoAgroStory";

export const metadata = { title: "Sampan Eco & Agro Resort | Sampan Group", description: "Sustainable farming, fresh produce and responsible rural experiences from Sampan Group." };
const gallery = ["/images/concerns/eco-agro.png", "/images/concerns/3-sampan-eco-agro.png", "/images/featuredConcerns/sampan-agro-golf-resort.png"];

export default function SampanEcoAgroPage() {
  return <main className="bg-[#f3f6f1] text-slate-900">
    <section className="relative flex min-h-screen items-end overflow-hidden bg-slate-950 text-white"><Image src="/images/concerns/eco-agro.png" alt="Sampan Eco & Agro landscape" fill priority className="object-cover opacity-65" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/45 to-transparent" /><div className="relative z-10 mx-auto w-full max-w-7xl px-6 pb-20 sm:px-10 lg:px-16"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.3em] text-emerald-300">Sampan hospitality &amp; agriculture</p><h1 className="max-w-4xl text-5xl font-semibold tracking-tight sm:text-7xl">Sampan Eco &amp; Agro Resort</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">A greener way to grow, gather and experience the countryside.</p></div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-6 py-24 sm:px-10 lg:grid-cols-[0.9fr_1.1fr] lg:px-16 lg:py-32"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-emerald-700">Our approach</p><h2 className="mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">Fresh from the soil, designed for tomorrow.</h2></div><div className="space-y-6 text-lg leading-8 text-slate-600"><p>Sampan Eco &amp; Agro brings together responsible farming, fresh produce and thoughtful rural hospitality in one living destination.</p><p>We nurture healthy soil, support local communities and create memorable experiences that connect people with nature.</p></div></section>
    <section className="bg-slate-950 px-6 py-24 text-white sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-emerald-300">Eco in action</p><h2 className="mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">A closer relationship with the land.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">From cultivation to the table, every step is guided by care, resourcefulness and respect for the environment.</p></div><div className="aspect-video overflow-hidden rounded-2xl border border-white/10 bg-black"><iframe className="h-full w-full" src="https://www.youtube.com/embed/ScMzIvxBSi4" title="Sampan Eco & Agro" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div></div></section>
    <EcoAgroStory />
    <section className="mx-auto max-w-7xl px-6 py-24 sm:px-10 lg:px-16 lg:py-32"><div className="mb-10 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-emerald-700">Explore the resort</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">A living, growing destination.</h2></div><p className="max-w-sm text-slate-600">Spaces and seasons shaped by nature, community and purposeful work.</p></div><div className="grid gap-5 md:grid-cols-3">{gallery.map((src, index) => <div key={src} className={`relative overflow-hidden rounded-2xl ${index === 1 ? "md:translate-y-10" : ""}`}><Image src={src} alt="Eco and agro resort" width={900} height={700} className="h-[22rem] w-full object-cover transition duration-700 hover:scale-105" /></div>)}</div></section>
    <section className="bg-emerald-900 px-6 py-20 text-white sm:px-10 lg:px-16"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 sm:flex-row sm:items-center"><div><p className="text-xs uppercase tracking-[0.28em] text-emerald-200">Plan a visit</p><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Come experience Sampan Eco &amp; Agro.</h2></div><Link href="/contact" className="inline-flex w-fit border border-white/60 px-6 py-3 text-sm font-semibold uppercase tracking-[0.16em] transition hover:bg-white hover:text-emerald-900">Contact us <span className="ml-3">→</span></Link></div></section>
  </main>;
}
